### ISSUE TITLE
Built the hybrid k-mer db

### ISSUE THREAD

**Issue by zhoudreames** [arangrhie/T2T-Polish#2]
in your article，you frist need to filtered error kmers for HiFi and illumina data，but there are no such step for it . Which method should I choose to build  the hybrid k-mer db？ thanks~
![image](https://user-images.githubusercontent.com/54714639/145027187-671b3d45-2cf0-49a8-95ea-42c30a1d22c4.png)

**Comment by arangrhie** [comment]
Hello @zhoudreames,

[This part](https://github.com/arangrhie/T2T-Polish/tree/master/merqury#2-hybrid) has the command lines used to generate the hybrid db.

Let me know if you have more questions.

**Comment by Johnsonzcode** [comment]
Sorry to reopen this thread.

Hi, @arangrhie , the [link](https://github.com/arangrhie/T2T-Polish/tree/master/merqury#2-hybrid) you provide which shows the step `Next, matching the diploid (2-copy) peak to 35x`. I don't know why `divide-round 3` and `increase 4` ?

Thank you in advance.

**Comment by pxxiao-hz** [comment]
I'm also confused about this parameter `divide-round 3 and increase 4`.
Can you explain it?

**Comment by arangrhie** [comment]
Huh, completely missed these questions. Sorry about that.
The `divide-round 3 and increase 4` was experimental, to derive the closest matching frequency for each copy numbers to mimic a kmer set from "one" platform to see if the frequency could be further utilized.

However, it did not work out well due to systematic biases in each platform.
It is ok to ignore this part as Merqury actually does not use any frequency info in QV estimation.
